version: "3"

services:
  backend:
    image: velodrome/api
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB3_PROVIDER_URI=https://velocimeter.tr.zone/
      - ROUTER_ADDRESS=0x2c8F86334552d062A0d7465C7f524eff15AB046c
      - FACTORY_ADDRESS=0xcC6AC37eafA77ef6C8b9283De89bE64d8030DCaE
      - VOTER_ADDRESS=0xd5FA5bfd83ea4A088a3A28E12AD6494750aC7B8c
      - VE_ADDRESS=0xA1B589FB7e04d19CEC391834131158f7F9d2D168
      - REWARDS_DIST_ADDRESS=0xF4A645eE46B06FEDEF7495B701117B58A2Db3A4C
      - TOKENLISTS=https://raw.githubusercontent.com/Velocimeter/docs/main/tokenlists/canto.json
      - DEFAULT_TOKEN_ADDRESS=0xbAD86785eB08fe9d0948B7D9d24523000A177cD0
      - OPTION_TOKEN_ADDRESS=0x5C2a258A169Fd683e784686E606E33f6D8c31b9a
      - STABLE_TOKEN_ADDRESS=0x80b5a32E4F032B2a058b4F29EC95EEfEEB87aDcd
      - ROUTE_TOKEN_ADDRESSES=0x826551890Dc65655a0Aceca109aB11AbDbD7a07B
      - SYNC_WAIT_SECONDS=20
      - IGNORED_TOKEN_ADDRESSES=0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000
      - SYNC_MAX_THREADS=1
      - PORT=3005
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
