version: "3"

services:
  backend:
    image: velodrome/api
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB3_PROVIDER_URI=https://1rpc.io/ftm
      - ROUTER_ADDRESS=0x2E14B53E2cB669f3A974CeaF6C735e134F3Aa9BC
      - FACTORY_ADDRESS=0x472f3C3c9608fe0aE8d702f3f8A2d12c410C881A
      - VOTER_ADDRESS=0xc9Ea7A2337f27935Cd3ccFB2f725B0428e731FBF
      - VE_ADDRESS=0xAE459eE7377Fb9F67518047BBA5482C2F0963236
      - REWARDS_DIST_ADDRESS=0xE0B708753aab9d2Cc142ea52Cd7CD0c923A3389A
      - TOKENLISTS=https://raw.githubusercontent.com/Velocimeter/frontend/fantom/mainnet-fantom-token-list.json
      - DEFAULT_TOKEN_ADDRESS=0x07BB65fAaC502d4996532F834A1B7ba5dC32Ff96
      - OPTION_TOKEN_ADDRESS=0xF9EDdca6B1e548B0EC8cDDEc131464F462b8310D
      - STABLE_TOKEN_ADDRESS=0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E
      - ROUTE_TOKEN_ADDRESSES=0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83
      - SYNC_WAIT_SECONDS=20
      - IGNORED_TOKEN_ADDRESSES=0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000
      - SYNC_MAX_THREADS=1
      - PORT=3005
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
