version: "3"

services:
  backend:
    image: velodrome/api
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB3_PROVIDER_URI=https://rpc.ankr.com/gnosis
      - ROUTER_ADDRESS=0x91aC12C15B8e9ac90d1585c7A586555d167cAb5B
      - FACTORY_ADDRESS=0x6738fF9bCE566b4F80bB604e18b9bA3B0daE60cA
      - VOTER_ADDRESS=0x34bAa0b40dc2Bd98c9fdDd5121Ba1bB855870338
      - VE_ADDRESS=0x762D6b449fFaC41DFDA9C9f3a22004F496cE7c80
      - REWARDS_DIST_ADDRESS=0x1097C568F5B6f25b0C97106DFB216e759572a2aE
      - TOKENLISTS=https://raw.githubusercontent.com/Velocimeter/docs/main/tokenlists/gnosis.json
      - DEFAULT_TOKEN_ADDRESS=0xE2244F3c62F4b313Cf9C5371c19E9ec9c89b8641
      - OPTION_TOKEN_ADDRESS=0x9240b391Be56f7845623057357aF5cf367cd762C
      - STABLE_TOKEN_ADDRESS=0x44fA8E6f47987339850636F88629646662444217
      - ROUTE_TOKEN_ADDRESSES=0xe91d153e0b41518a2ce8dd3d7944fa863463a97d
      - SYNC_WAIT_SECONDS=20
      - IGNORED_TOKEN_ADDRESSES=0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000
      - SYNC_MAX_THREADS=1
      - PORT=3005
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
