version: "3"

services:
  backend:
    image: velodrome/api
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB3_PROVIDER_URI=https://mainnet.base.org/
      - ROUTER_ADDRESS=0xE11b93B61f6291d35c5a2beA0A9fF169080160cF
      - FACTORY_ADDRESS=0xe21Aac7F113Bd5DC2389e4d8a8db854a87fD6951
      - VOTER_ADDRESS=0xab9B68c9e53c94D7c0949FB909E80e4a29F9134A
      - VE_ADDRESS=0x91F85d68B413dE823684c891db515B0390a02512
      - REWARDS_DIST_ADDRESS=0x71Eaf68c2A23b7Bd78Db4987c3eCdB41c3b3b388
      - TOKENLISTS=https://raw.githubusercontent.com/Velocimeter/docs/main/tokenlists/base.json
      - DEFAULT_TOKEN_ADDRESS=0xd386a121991E51Eab5e3433Bf5B1cF4C8884b47a
      - OPTION_TOKEN_ADDRESS=0x762eb51D2e779EeEc9B239FFB0B2eC8262848f3E
      - STABLE_TOKEN_ADDRESS=0x0b776552c1aef1dc33005dd25acda22493b6615d
      - ROUTE_TOKEN_ADDRESSES=0x4200000000000000000000000000000000000006
      - SYNC_WAIT_SECONDS=20
      - IGNORED_TOKEN_ADDRESSES=0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000
      - SYNC_MAX_THREADS=1
      - PORT=3005
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
