version: "3"

services:
  backend:
    image: velodrome/api
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB3_PROVIDER_URI=https://sepolia-rpc.scroll.io/
      - ROUTER_ADDRESS=0xda88794Bd073de116a842e5a4add523Cd76C9E73
      - FACTORY_ADDRESS=0x83A7d44861f28940D9c5Fa22ce1b91CFb66dAb6B
      - VOTER_ADDRESS=0xE9B9A807C465904612B72a130E2D9662DDE230FB
      - VE_ADDRESS=0x917383C52e4357965e99e411a39cbD240f4C9061
      - REWARDS_DIST_ADDRESS=0x856b9dF51D5B4Da08D551499d9Fa78BC06A8Dc0F
      - TOKENLISTS=https://raw.githubusercontent.com/Velocimeter/docs/main/tokenlists/scroll-testnet.json
      - DEFAULT_TOKEN_ADDRESS=0x5fC02571D53A9B71cE8F5063307367d6fD2caf85
      - OPTION_TOKEN_ADDRESS=0xb55478715D80391B63c7D24362a2399B6AE62788
      - STABLE_TOKEN_ADDRESS=0xFfd2eCE82f7959ae184D10fe17865d27B4f0FB94
      - ROUTE_TOKEN_ADDRESSES=0x5300000000000000000000000000000000000004
      - SYNC_WAIT_SECONDS=20
      - IGNORED_TOKEN_ADDRESSES=0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000
      - SYNC_MAX_THREADS=1
      - PORT=3005
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
